export { default as Home } from './Home'
export { default as Cart } from './Cart'
export { default as SingleItem } from './SingleItem'
export { default as Delivery } from './Delivery'
export { default as Options } from './Options'
export { default as InRestaurant } from './InRestaurant'
export { default as OrderDetails } from './OrderDetails'
export { default as TrackOrder } from './TrackOrder'
export { default as Landing } from './Landing'
export { default as NotFound } from "./NotFound";
export { default as About } from "./About";
